// default package
// Generated 20.08.2015 13:23:16 by Hibernate Tools 4.3.1
package com.saucelabs.Tests.DBTests.dataBaseTests.entities;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Problemtypes generated by hbm2java
 */
@Entity
@Table(name = "ProblemTypes", catalog = "Enviromap")
public class ProblemTypes implements java.io.Serializable {

	private Integer id;
	private String type;
	private Set<Problems> problemses = new HashSet<Problems>(0);

	public ProblemTypes() {
	}

	public ProblemTypes(String type, Set<Problems> problemses) {
		this.type = type;
		this.problemses = problemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "problemTypes")
	public Set<Problems> getProblemses() {
		return this.problemses;
	}

	public void setProblemses(Set<Problems> problemses) {
		this.problemses = problemses;
	}

}
