// default package
// Generated 20.08.2015 13:23:16 by Hibernate Tools 4.3.1
package com.saucelabs.Tests.DBTests.entities;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Photos generated by hbm2java
 */
@Entity
@Table(name = "photos", catalog = "enviromap")
public class Photos implements java.io.Serializable {

	private PhotosId id;
	private Problems problems;
	private Users users;
	private String link;
	private Boolean status;
	private String description;

	public Photos() {
	}

	public Photos(PhotosId id, Problems problems) {
		this.id = id;
		this.problems = problems;
	}

	public Photos(PhotosId id, Problems problems, Users users, String link,
			Boolean status, String description) {
		this.id = id;
		this.problems = problems;
		this.users = users;
		this.link = link;
		this.status = status;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "problemsId", column = @Column(name = "Problems_Id", nullable = false)) })

	public PhotosId getId() {
		return this.id;
	}

	public void setId(PhotosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Problems_Id", nullable = false, insertable = false, updatable = false)
	public Problems getProblems() {
		return this.problems;
	}

	public void setProblems(Problems problems) {
		this.problems = problems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_Id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Link", length = 100)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "Description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
