// default package
// Generated 20.08.2015 13:23:16 by Hibernate Tools 4.3.1
package com.saucelabs.Tests.DBTests.entities;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhotosId generated by hbm2java
 */
@Embeddable
public class PhotosId implements java.io.Serializable {

	private int id;
	private int problemsId;

	public PhotosId() {
	}

	public PhotosId(int id, int problemsId) {
		this.id = id;
		this.problemsId = problemsId;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Problems_Id", nullable = false)
	public int getProblemsId() {
		return this.problemsId;
	}

	public void setProblemsId(int problemsId) {
		this.problemsId = problemsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhotosId))
			return false;
		PhotosId castOther = (PhotosId) other;

		return (this.getId() == castOther.getId())
				&& (this.getProblemsId() == castOther.getProblemsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getProblemsId();
		return result;
	}

}
