// default package
// Generated 20.08.2015 13:23:16 by Hibernate Tools 4.3.1
package com.saucelabs.Tests.DBTests.entities;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Problems generated by hbm2java
 */
@Entity
@Table(name = "problems", catalog = "enviromap")
public class Problems implements java.io.Serializable {

	private Integer id;
	private Problemtypes problemtypes;
	private String title;
	private String content;
	private String proposal;
	private Byte severity;
	private Boolean moderation;
	private Short votes;
	private Float latitude;
	private Float longtitude;
	private Boolean status;
	private Set<Activities> activitieses = new HashSet<Activities>(0);
	private Set<Photos> photoses = new HashSet<Photos>(0);

	public Problems() {
	}

	public Problems(Problemtypes problemtypes) {
		this.problemtypes = problemtypes;
	}

	public Problems(Problemtypes problemtypes, String title, String content,
			String proposal, Byte severity, Boolean moderation, Short votes,
			Float latitude, Float longtitude, Boolean status,
			Set<Activities> activitieses, Set<Photos> photoses) {
		this.problemtypes = problemtypes;
		this.title = title;
		this.content = content;
		this.proposal = proposal;
		this.severity = severity;
		this.moderation = moderation;
		this.votes = votes;
		this.latitude = latitude;
		this.longtitude = longtitude;
		this.status = status;
		this.activitieses = activitieses;
		this.photoses = photoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProblemTypes_Id", nullable = false)
	public Problemtypes getProblemtypes() {
		return this.problemtypes;
	}

	public void setProblemtypes(Problemtypes problemtypes) {
		this.problemtypes = problemtypes;
	}

	@Column(name = "Title", length = 130)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Content", length = 5000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "Proposal", length = 5000)
	public String getProposal() {
		return this.proposal;
	}

	public void setProposal(String proposal) {
		this.proposal = proposal;
	}

	@Column(name = "Severity")
	public Byte getSeverity() {
		return this.severity;
	}

	public void setSeverity(Byte severity) {
		this.severity = severity;
	}

	@Column(name = "Moderation")
	public Boolean getModeration() {
		return this.moderation;
	}

	public void setModeration(Boolean moderation) {
		this.moderation = moderation;
	}

	@Column(name = "Votes")
	public Short getVotes() {
		return this.votes;
	}

	public void setVotes(Short votes) {
		this.votes = votes;
	}

	@Column(name = "Latitude", precision = 9, scale = 6)
	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longtitude", precision = 9, scale = 6)
	public Float getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(Float longtitude) {
		this.longtitude = longtitude;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "problems")
	public Set<Activities> getActivitieses() {
		return this.activitieses;
	}

	public void setActivitieses(Set<Activities> activitieses) {
		this.activitieses = activitieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "problems")
	public Set<Photos> getPhotoses() {
		return this.photoses;
	}

	public void setPhotoses(Set<Photos> photoses) {
		this.photoses = photoses;
	}

}
