// default package
// Generated 20.08.2015 13:23:16 by Hibernate Tools 4.3.1
package com.saucelabs.Tests.DBTests.entities;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name = "resources", catalog = "enviromap", uniqueConstraints = {
		@UniqueConstraint(columnNames = "Alias"),
		@UniqueConstraint(columnNames = "Title") })
public class Resources implements java.io.Serializable {

	private Integer id;
	private String alias;
	private String title;
	private String content;
	private boolean isResource;

	public Resources() {
	}

	public Resources(String alias, String title, String content,
			boolean isResource) {
		this.alias = alias;
		this.title = title;
		this.content = content;
		this.isResource = isResource;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Alias", unique = true, nullable = false, length = 30)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "Title", unique = true, nullable = false, length = 150)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Content", nullable = false, length = 10000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "IsResource", nullable = false)
	public boolean isIsResource() {
		return this.isResource;
	}

	public void setIsResource(boolean isResource) {
		this.isResource = isResource;
	}

}
